import { test, type Browser } from "@playwright/test";
import pg from "pg";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { createTestApi } from "./helpers";

const BASE = process.env.PLAYWRIGHT_BASE_URL ?? "http://localhost:3000";
const DB = process.env.DATABASE_URL ?? "postgres://multica:multica@localhost:5432/multica?sslmode=disable";
const OUT = process.env.SCREENSHOT_DIR ?? "artifacts/multica-rich-dark-screenshots";
const NIL = "00000000-0000-0000-0000-000000000000";
type Row={template:string;requestedUrl:string;finalUrl:string;status:number|null;screenshot:string;title:string;note:string;error:string};

function filename(template:string,index:number){const slug=template==="/"?"root":template.replace(/^\//,"").replace(/\[([^\]]+)\]/g,"$1").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/^-+|-+$/g,"");return `${String(index+1).padStart(2,"0")}-${slug}.png`;}
async function manifests(rows:Row[]){await writeFile(join(OUT,"manifest.json"),JSON.stringify(rows,null,2)+"\n");const cols:(keyof Row)[]=["template","requestedUrl","finalUrl","status","screenshot","title","note","error"];const q=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;await writeFile(join(OUT,"manifest.csv"),[cols.join(","),...rows.map(r=>cols.map(k=>q(r[k])).join(","))].join("\n")+"\n");}
async function capture(browser:Browser,token:string|null,template:string,path:string,index:number,note:string,rows:Row[]){const ctx=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:"dark"});if(token)await ctx.addInitScript(t=>{localStorage.setItem("multica_token",t);localStorage.setItem("multica:chat:isOpen","false");},token);const page=await ctx.newPage();const requestedUrl=new URL(path,BASE).toString();const screenshot=filename(template,index);let status:number|null=null,error="",title="";try{const r=await page.goto(requestedUrl,{waitUntil:"domcontentloaded",timeout:20000});status=r?.status()??null;await page.waitForLoadState("networkidle",{timeout:4000}).catch(()=>{});await page.waitForTimeout(700);}catch(e){error=e instanceof Error?e.message:String(e);}try{title=await page.title();}catch{}try{await page.screenshot({path:join(OUT,screenshot),fullPage:true,animations:"disabled",timeout:20000});}catch(e){const m=e instanceof Error?e.message:String(e);error=error?`${error} | screenshot: ${m}`:`screenshot: ${m}`;}rows.push({template,requestedUrl,finalUrl:page.url(),status,screenshot,title,note,error});await manifests(rows);await ctx.close().catch(()=>{});}

test("rich workspace dark screenshots",async({browser})=>{
  test.setTimeout(15*60_000);await mkdir(OUT,{recursive:true});
  const api=await createTestApi();const workspace=(await api.getWorkspaces())[0];if(!workspace)throw new Error("workspace missing");api.setWorkspaceId(workspace.id);api.setWorkspaceSlug(workspace.slug);const token=api.getToken();if(!token)throw new Error("token missing");
  const issues=await api.seedTableIssues([
    {title:"Implement OAuth callback validation",status:"in_progress",priority:"urgent"},{title:"Fix flaky task cancellation",status:"in_review",priority:"high"},{title:"Add runtime heartbeat metrics",status:"todo",priority:"medium"},{title:"Investigate context window regression",status:"blocked",priority:"high"},{title:"Ship agent usage dashboard",status:"done",priority:"medium"},{title:"Document squad handoff flow",status:"backlog",priority:"low"},{title:"Reduce cold-start latency",status:"in_progress",priority:"high"},{title:"Review plugin permission model",status:"in_review",priority:"medium"},{title:"Improve issue search relevance",status:"todo",priority:"medium"},{title:"Handle stale runtime disconnects",status:"done",priority:"high"},{title:"Prototype release-note agent",status:"backlog",priority:"low"},{title:"Repair webhook retry backoff",status:"blocked",priority:"urgent"}
  ]);
  const db=new pg.Client(DB);await db.connect();const warnings:string[]=[];const safe=async<T>(label:string,fn:()=>Promise<T>,fallback:T):Promise<T>=>{try{return await fn();}catch(e){const m=`${label}: ${e instanceof Error?e.message:String(e)}`;warnings.push(m);console.warn(m);return fallback;}};const id=async(label:string,sql:string,params:unknown[]=[])=>safe(label,async()=>{const r=await db.query<{id:string}>(sql,params);return r.rows[0]?.id??NIL;},NIL);
  const userId=await id("user",`SELECT id::text AS id FROM "user" WHERE email=$1 LIMIT 1`,[api.getEmail()]);const memberId=await id("member",`SELECT id::text AS id FROM member WHERE workspace_id=$1 AND user_id=$2 LIMIT 1`,[workspace.id,userId]);
  const runtimeA=await id("runtime A",`INSERT INTO agent_runtime (workspace_id,daemon_id,name,runtime_mode,provider,status,device_info,metadata,last_seen_at) VALUES ($1,NULL,'Mac Studio — Codex','cloud','codex','online','macOS arm64','{"cpu":"Apple M4 Max","memory":"64 GB"}'::jsonb,now()) RETURNING id::text AS id`,[workspace.id]);
  const runtimeB=await id("runtime B",`INSERT INTO agent_runtime (workspace_id,daemon_id,name,runtime_mode,provider,status,device_info,metadata,last_seen_at) VALUES ($1,NULL,'Linux Builder — Claude','cloud','claude_code','online','Ubuntu 24.04 x86_64','{"cpu":"16 vCPU","memory":"32 GB"}'::jsonb,now()-interval '8 seconds') RETURNING id::text AS id`,[workspace.id]);
  const runtimeC=await id("runtime C",`INSERT INTO agent_runtime (workspace_id,daemon_id,name,runtime_mode,provider,status,device_info,metadata,last_seen_at) VALUES ($1,NULL,'CI Runner — Gemini','cloud','gemini_cli','online','GitHub Actions Linux','{"cpu":"4 vCPU","memory":"16 GB"}'::jsonb,now()-interval '25 seconds') RETURNING id::text AS id`,[workspace.id]);
  const agentA=await id("agent A",`INSERT INTO agent (workspace_id,name,description,instructions,runtime_mode,runtime_config,runtime_id,visibility,status,max_concurrent_tasks,owner_id) VALUES ($1,'Backend Engineer','Owns API reliability and database work','Keep changes small, tested, and production-safe.','cloud','{}'::jsonb,$2,'workspace','working',3,$3) RETURNING id::text AS id`,[workspace.id,runtimeA,userId]);
  const agentB=await id("agent B",`INSERT INTO agent (workspace_id,name,description,instructions,runtime_mode,runtime_config,runtime_id,visibility,status,max_concurrent_tasks,owner_id) VALUES ($1,'Frontend Engineer','Builds product UI and interaction polish','Prefer accessible components and strong loading states.','cloud','{}'::jsonb,$2,'workspace','working',2,$3) RETURNING id::text AS id`,[workspace.id,runtimeB,userId]);
  const agentC=await id("agent C",`INSERT INTO agent (workspace_id,name,description,instructions,runtime_mode,runtime_config,runtime_id,visibility,status,max_concurrent_tasks,owner_id) VALUES ($1,'Code Reviewer','Reviews risky changes and test coverage','Prioritize correctness, regressions, and security.','cloud','{}'::jsonb,$2,'workspace','idle',2,$3) RETURNING id::text AS id`,[workspace.id,runtimeC,userId]);
  const agentD=await id("agent D",`INSERT INTO agent (workspace_id,name,description,instructions,runtime_mode,runtime_config,runtime_id,visibility,status,max_concurrent_tasks,owner_id) VALUES ($1,'Release Captain','Coordinates releases and incident follow-up','Surface blockers early and keep release notes current.','cloud','{}'::jsonb,$2,'workspace','blocked',1,$3) RETURNING id::text AS id`,[workspace.id,runtimeB,userId]);
  await safe("daemon connections",()=>db.query(`INSERT INTO daemon_connection (agent_id,daemon_id,status,last_heartbeat_at,runtime_info) VALUES ($1,'seed-backend','connected',now(),'{"version":"0.4.43"}'::jsonb),($2,'seed-frontend','connected',now()-interval '5 seconds','{"version":"0.4.43"}'::jsonb)`,[agentA,agentB]),undefined);
  const projectA=await id("project A",`INSERT INTO project (workspace_id,title,description,icon,status,lead_type,lead_id) VALUES ($1,'Agent Platform','Core runtime, orchestration, and reliability work','bot','in_progress','agent',$2) RETURNING id::text AS id`,[workspace.id,agentA]);const projectB=await id("project B",`INSERT INTO project (workspace_id,title,description,icon,status,lead_type,lead_id) VALUES ($1,'Web Experience','Workspace UI, collaboration, and onboarding','sparkles','in_progress','agent',$2) RETURNING id::text AS id`,[workspace.id,agentB]);
  const assignments=[[issues[0]!.id,agentA,projectA],[issues[1]!.id,agentC,projectA],[issues[2]!.id,agentA,projectA],[issues[3]!.id,agentD,projectA],[issues[4]!.id,agentB,projectB],[issues[5]!.id,agentB,projectB],[issues[6]!.id,agentB,projectB],[issues[7]!.id,agentC,projectA],[issues[8]!.id,agentB,projectB],[issues[9]!.id,agentA,projectA],[issues[10]!.id,agentD,projectB],[issues[11]!.id,agentD,projectA]];for(const [issueId,agentId,projectId] of assignments)await db.query(`UPDATE issue SET assignee_type='agent',assignee_id=$2,project_id=$3,updated_at=now() WHERE id=$1`,[issueId,agentId,projectId]);
  const runningA=await id("running A",`INSERT INTO agent_task_queue (agent_id,runtime_id,issue_id,status,priority,dispatched_at,started_at,created_at) VALUES ($1,$2,$3,'running',100,now()-interval '9 minutes',now()-interval '8 minutes',now()-interval '10 minutes') RETURNING id::text AS id`,[agentA,runtimeA,issues[0]!.id]);
  const runningB=await id("running B",`INSERT INTO agent_task_queue (agent_id,runtime_id,issue_id,status,priority,dispatched_at,started_at,created_at) VALUES ($1,$2,$3,'running',80,now()-interval '5 minutes',now()-interval '4 minutes',now()-interval '6 minutes') RETURNING id::text AS id`,[agentB,runtimeB,issues[6]!.id]);
  await id("dispatched",`INSERT INTO agent_task_queue (agent_id,runtime_id,issue_id,status,priority,dispatched_at,created_at) VALUES ($1,$2,$3,'dispatched',60,now()-interval '90 seconds',now()-interval '2 minutes') RETURNING id::text AS id`,[agentC,runtimeC,issues[1]!.id]);
  const completed=await id("completed",`INSERT INTO agent_task_queue (agent_id,runtime_id,issue_id,status,priority,dispatched_at,started_at,completed_at,result,created_at) VALUES ($1,$2,$3,'completed',50,now()-interval '42 minutes',now()-interval '41 minutes',now()-interval '18 minutes','{"summary":"Added heartbeat metrics and tests","filesChanged":6}'::jsonb,now()-interval '43 minutes') RETURNING id::text AS id`,[agentA,runtimeA,issues[9]!.id]);
  const failed=await id("failed",`INSERT INTO agent_task_queue (agent_id,runtime_id,issue_id,status,priority,dispatched_at,started_at,completed_at,error,created_at) VALUES ($1,$2,$3,'failed',95,now()-interval '31 minutes',now()-interval '30 minutes',now()-interval '27 minutes','Integration test failed after webhook provider returned 429',now()-interval '32 minutes') RETURNING id::text AS id`,[agentD,runtimeB,issues[11]!.id]);
  await id("queued",`INSERT INTO agent_task_queue (agent_id,runtime_id,issue_id,status,priority,created_at) VALUES ($1,$2,$3,'queued',40,now()-interval '30 seconds') RETURNING id::text AS id`,[agentC,runtimeC,issues[7]!.id]);
  await safe("comments",()=>db.query(`INSERT INTO comment (workspace_id,issue_id,author_type,author_id,content,type,created_at) VALUES ($1,$2,'agent',$6,'I traced the callback mismatch to state validation. Implementing the fix and adding regression coverage now.','progress_update',now()-interval '6 minutes'),($1,$2,'member',$7,'Please keep backward compatibility for existing OAuth installs.','comment',now()-interval '4 minutes'),($1,$3,'agent',$8,'Review found one cancellation race around terminal task settlement.','comment',now()-interval '12 minutes'),($1,$4,'agent',$6,'Heartbeat metrics are merged; watching runtime churn before closing.','progress_update',now()-interval '22 minutes'),($1,$5,'agent',$9,'Blocked on reproducing the context regression with the current provider build.','progress_update',now()-interval '18 minutes')`,[workspace.id,issues[0]!.id,issues[1]!.id,issues[2]!.id,issues[3]!.id,agentA,userId,agentC,agentD]),undefined);
  const skillA=await id("skill A",`INSERT INTO skill (workspace_id,name,description,content,config,created_by) VALUES ($1,'PostgreSQL Debugging','Investigate query plans, locks, and migration failures','# PostgreSQL Debugging\n\nInspect plans, locks, constraints, and migration history before changing data.','{}'::jsonb,$2) RETURNING id::text AS id`,[workspace.id,userId]);const skillB=await id("skill B",`INSERT INTO skill (workspace_id,name,description,content,config,created_by) VALUES ($1,'Frontend QA','Systematically verify visual, accessibility, and interaction regressions','# Frontend QA\n\nCheck responsive layouts, keyboard access, loading states, and regressions.','{}'::jsonb,$2) RETURNING id::text AS id`,[workspace.id,userId]);await safe("agent skills",()=>db.query(`INSERT INTO agent_skill (agent_id,skill_id) VALUES ($1,$3),($2,$4) ON CONFLICT DO NOTHING`,[agentA,agentB,skillA,skillB]),undefined);
  const squad=await id("squad",`INSERT INTO squad (workspace_id,name,description,leader_id,creator_id) VALUES ($1,'Platform Squad','Backend engineer, reviewer, and release captain working as one delivery unit',$2,$3) RETURNING id::text AS id`,[workspace.id,agentA,userId]);await safe("squad members",()=>db.query(`INSERT INTO squad_member (squad_id,member_type,member_id,role) VALUES ($1,'agent',$2,'lead'),($1,'agent',$3,'reviewer'),($1,'agent',$4,'release') ON CONFLICT DO NOTHING`,[squad,agentA,agentC,agentD]),undefined);
  const autopilot=await id("autopilot",`INSERT INTO autopilot (workspace_id,title,description,assignee_type,assignee_id,status,execution_mode,issue_title_template,project_id,created_by_type,created_by_id,last_run_at) VALUES ($1,'Nightly reliability sweep','Inspect runtime health and open a focused reliability issue when action is needed','agent',$2,'active','create_issue','Nightly reliability findings',$3,'member',$4,now()-interval '1 day') RETURNING id::text AS id`,[workspace.id,agentA,projectA,userId]);
  const trigger=await id("trigger",`INSERT INTO autopilot_trigger (autopilot_id,kind,enabled,cron_expression,timezone,next_run_at,label,published_by_type,published_by_id,created_by_type,created_by_id,last_fired_at) VALUES ($1,'schedule',true,'0 2 * * *','Europe/Amsterdam',now()+interval '5 hours','Nightly at 02:00','member',$2,'member',$2,now()-interval '1 day') RETURNING id::text AS id`,[autopilot,userId]);
  const runDone=await id("run completed",`INSERT INTO autopilot_run (autopilot_id,trigger_id,source,status,issue_id,task_id,triggered_at,completed_at,result) VALUES ($1,$2,'schedule','completed',$3,$4,now()-interval '1 day',now()-interval '23 hours 42 minutes','{"summary":"Heartbeat drift found and repaired"}'::jsonb) RETURNING id::text AS id`,[autopilot,trigger,issues[9]!.id,completed]);const runLive=await id("run running",`INSERT INTO autopilot_run (autopilot_id,trigger_id,source,status,issue_id,task_id,triggered_at) VALUES ($1,$2,'manual','running',$3,$4,now()-interval '8 minutes') RETURNING id::text AS id`,[autopilot,trigger,issues[0]!.id,runningA]);await id("run failed",`INSERT INTO autopilot_run (autopilot_id,trigger_id,source,status,issue_id,task_id,triggered_at,completed_at,failure_reason) VALUES ($1,$2,'api','failed',$3,$4,now()-interval '3 days',now()-interval '3 days'+interval '4 minutes','Provider rate limit exhausted') RETURNING id::text AS id`,[autopilot,trigger,issues[11]!.id,failed]);if(runLive!==NIL)await db.query(`UPDATE agent_task_queue SET autopilot_run_id=$2 WHERE id=$1`,[runningA,runLive]);if(runDone!==NIL)await db.query(`UPDATE agent_task_queue SET autopilot_run_id=$2 WHERE id=$1`,[completed,runDone]);
  const chat=await id("chat",`INSERT INTO chat_session (workspace_id,agent_id,creator_id,title,status) VALUES ($1,$2,$3,'OAuth callback incident','active') RETURNING id::text AS id`,[workspace.id,agentA,userId]);await safe("chat",()=>db.query(`INSERT INTO chat_message (chat_session_id,role,content,created_at,quick_actions) VALUES ($1,'user','Can you investigate why OAuth callbacks started failing after the last deployment?',now()-interval '11 minutes','[]'::jsonb),($1,'assistant','I found the regression in callback state validation. I have a fix in progress and I am adding compatibility coverage before marking it ready for review.',now()-interval '9 minutes',$2::jsonb),($1,'user','Keep compatibility with existing installs and flag anything that needs a migration.',now()-interval '7 minutes','[]'::jsonb)`,[chat,JSON.stringify([{label:"Show current diff",prompt:"Show me the current diff and remaining risks.",primary:true},{label:"Summarize tests",prompt:"Summarize the regression tests you added."}])]),undefined);
  await safe("inbox",()=>db.query(`INSERT INTO inbox_item (workspace_id,recipient_type,recipient_id,type,severity,issue_id,title,body,read,archived,created_at) VALUES ($1,'member',$2,'review','action_required',$3,'Review requested: OAuth callback validation','Backend Engineer finished the first implementation pass and requested review.',false,false,now()-interval '3 minutes'),($1,'member',$2,'agent_update','attention',$4,'Release Captain is blocked','Context regression reproduction needs a fresh provider build.',false,false,now()-interval '17 minutes'),($1,'member',$2,'run_complete','info',$5,'Nightly reliability sweep completed','Runtime heartbeat drift was detected and repaired.',true,false,now()-interval '23 hours')`,[workspace.id,memberId,issues[0]!.id,issues[3]!.id,issues[9]!.id]),undefined);
  const scalar=async(sql:string,p:unknown[]=[])=>Number((await db.query(sql,p)).rows[0]?.count??0);const summary={workspace:{id:workspace.id,slug:workspace.slug},workingAgents:await scalar(`SELECT count(*) FROM agent WHERE workspace_id=$1 AND status='working'`,[workspace.id]),onlineRuntimes:await scalar(`SELECT count(*) FROM agent_runtime WHERE workspace_id=$1 AND status='online'`,[workspace.id]),runningTasks:await scalar(`SELECT count(*) FROM agent_task_queue q JOIN agent a ON a.id=q.agent_id WHERE a.workspace_id=$1 AND q.status='running'`,[workspace.id]),dispatchedTasks:await scalar(`SELECT count(*) FROM agent_task_queue q JOIN agent a ON a.id=q.agent_id WHERE a.workspace_id=$1 AND q.status='dispatched'`,[workspace.id]),queuedTasks:await scalar(`SELECT count(*) FROM agent_task_queue q JOIN agent a ON a.id=q.agent_id WHERE a.workspace_id=$1 AND q.status='queued'`,[workspace.id]),completedTasks:await scalar(`SELECT count(*) FROM agent_task_queue q JOIN agent a ON a.id=q.agent_id WHERE a.workspace_id=$1 AND q.status='completed'`,[workspace.id]),failedTasks:await scalar(`SELECT count(*) FROM agent_task_queue q JOIN agent a ON a.id=q.agent_id WHERE a.workspace_id=$1 AND q.status='failed'`,[workspace.id]),issues:await scalar(`SELECT count(*) FROM issue WHERE workspace_id=$1`,[workspace.id]),comments:await scalar(`SELECT count(*) FROM comment WHERE workspace_id=$1`,[workspace.id]),projects:await scalar(`SELECT count(*) FROM project WHERE workspace_id=$1`,[workspace.id]),skills:await scalar(`SELECT count(*) FROM skill WHERE workspace_id=$1`,[workspace.id]),squads:await scalar(`SELECT count(*) FROM squad WHERE workspace_id=$1`,[workspace.id]),autopilots:await scalar(`SELECT count(*) FROM autopilot WHERE workspace_id=$1`,[workspace.id]),autopilotRuns:await scalar(`SELECT count(*) FROM autopilot_run r JOIN autopilot a ON a.id=r.autopilot_id WHERE a.workspace_id=$1`,[workspace.id]),chatMessages:await scalar(`SELECT count(*) FROM chat_message m JOIN chat_session s ON s.id=m.chat_session_id WHERE s.workspace_id=$1`,[workspace.id]),inboxItems:await scalar(`SELECT count(*) FROM inbox_item WHERE workspace_id=$1`,[workspace.id]),warnings};await writeFile(join(OUT,"seed-summary.json"),JSON.stringify(summary,null,2)+"\n");if(summary.workingAgents<2||summary.runningTasks<2||summary.onlineRuntimes<3||summary.autopilotRuns<3||summary.comments<4)throw new Error(`rich seed incomplete: ${JSON.stringify(summary)}`);
  const pub:[string,string,string?][]=[["/","/"],["/homepage","/homepage"],["/about","/about"],["/changelog","/changelog"],["/contact-sales","/contact-sales"],["/download","/download"],["/usecases","/usecases"],["/usecases/[slug]","/usecases/auto-data-analysis"],["/invitations","/invitations"],["/invite/[id]",`/invite/${NIL}`],["/login","/login"],["/onboarding","/onboarding"],["/workspaces/new","/workspaces/new"],["/auth/callback","/auth/callback?error=access_denied"],["/billing/return","/billing/return?session_id=screenshot"],["/join","/join"],["/dingtalk/bind","/dingtalk/bind"],["/lark/bind","/lark/bind"],["/slack/bind","/slack/bind"],["/telegram/bind","/telegram/bind"],["/wecom/bind","/wecom/bind"]];const ws=`/${workspace.slug}`;const auth:[string,string,string?][]=[["/[workspaceSlug]/agents",`${ws}/agents`,"4 agents: 2 working, 1 idle, 1 blocked"],["/[workspaceSlug]/agents/[id]",`${ws}/agents/${agentA}`,"Working agent with active run"],["/[workspaceSlug]/agents/new",`${ws}/agents/new`],["/[workspaceSlug]/agents/new/ai",`${ws}/agents/new/ai`],["/[workspaceSlug]/agents/new/ai/[sessionId]",`${ws}/agents/new/ai/${NIL}`],["/[workspaceSlug]/agents/new/manual",`${ws}/agents/new/manual`],["/[workspaceSlug]/autopilots",`${ws}/autopilots`,"3 run outcomes"],["/[workspaceSlug]/autopilots/[id]",`${ws}/autopilots/${autopilot}`],["/[workspaceSlug]/billing",`${ws}/billing`],["/[workspaceSlug]/chat",`${ws}/chat?session=${chat}`],["/[workspaceSlug]/inbox",`${ws}/inbox`],["/[workspaceSlug]/issues",`${ws}/issues`,"12 issues across workflow states"],["/[workspaceSlug]/issues/[id]",`${ws}/issues/${issues[0]!.id}`],["/[workspaceSlug]/members/[id]",`${ws}/members/${userId}`],["/[workspaceSlug]/my-issues",`${ws}/my-issues`],["/[workspaceSlug]/projects",`${ws}/projects`],["/[workspaceSlug]/projects/[id]",`${ws}/projects/${projectA}`],["/[workspaceSlug]/runtimes",`${ws}/runtimes`,"3 online runtimes"],["/[workspaceSlug]/runtimes/[id]",`${ws}/runtimes/${runtimeA}`],["/[workspaceSlug]/runtimes/[id]/runtime/[runtimeId]",`${ws}/runtimes/${runtimeA}/runtime/${runtimeA}`],["/[workspaceSlug]/settings",`${ws}/settings`],["/[workspaceSlug]/skills",`${ws}/skills`],["/[workspaceSlug]/skills/[id]",`${ws}/skills/${skillA}`],["/[workspaceSlug]/squads",`${ws}/squads`],["/[workspaceSlug]/squads/[id]",`${ws}/squads/${squad}`],["/[workspaceSlug]/usage",`${ws}/usage`],["/[workspaceSlug]/attachments/[id]/preview",`${ws}/attachments/${NIL}/preview`]];const rows:Row[]=[];let n=0;for(const[t,p,note=""]of pub)await capture(browser,null,t,p,n++,note,rows);for(const[t,p,note=""]of auth)await capture(browser,token,t,p,n++,note,rows);await db.end();
});